/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./Coin.gltf -t
*/

import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Circle003: THREE.Mesh;
    Circle003_1: THREE.Mesh;
    Text001: THREE.Mesh;
    Plane001: THREE.Mesh;
  };
  materials: {
    Gold: THREE.MeshStandardMaterial;
    ['Gold.bump']: THREE.MeshStandardMaterial;
  };
};

export function Coin(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./coin.gltf') as GLTFResult;
  return (
    <group {...props} dispose={null} scale={0.75}>
      <group position={[0, 0, -0.048]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Circle003.geometry} material={materials.Gold} />
        <mesh
          geometry={nodes.Circle003_1.geometry}
          material={materials['Gold.bump']}
        />
      </group>
      <mesh
        geometry={nodes.Text001.geometry}
        material={materials.Gold}
        position={[-0.003, 0.011, -0.026]}
        rotation={[Math.PI / 2, 0.926, 0]}
        scale={0.092}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials.Gold}
        position={[0.026, 0.049, -0.025]}
        scale={0.567}
      />
    </group>
  );
}

useGLTF.preload('/Coin.gltf');
