// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  12

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    contract
    (
        init => init
        issueToken1 => issue_token1
        mint => mint
        burn => burn
        deposit => deposit
        deploymentBlock => deployment_block
        getBlockDeposits => block_deposits
        getDepositAmount => deposit_amount
        getDepositAddress => deposit_address
        getDepositTokenId => deposit_token_id
        getToken1 => token_1
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
